const geminiService = require('../services/geminiService');
const ChatMessage = require('../models/ChatMessage');
const User = require('../models/User');
const fs = require('fs');
const path = require('path');
const pdf = require('pdf-parse');
const mammoth = require('mammoth');
const { findSessionByIdOrCustomId } = require('../utils/sessionHelper');

// @desc    Download session summary as text
// @route   GET /api/ai/session-summary/:id/download
// @access  Private
exports.downloadSummary = async (req, res) => {
  try {
    const Session = require('../models/Session');
    const session = await Session.findById(req.params.id);
    if (!session || !session.aiSummary) {
      return res.status(404).json({ success: false, message: 'Summary not found' });
    }

    let aiSummary;
    try {
      aiSummary = JSON.parse(session.aiSummary);
    } catch (parseError) {
      aiSummary = { summary: session.aiSummary, keyTakeaways: [], tasks: [] };
    }

    const content = `
SkillXchange Session Summary
===========================
Topic: ${session.topic}
Date: ${new Date(session.scheduledTime).toLocaleDateString()}
Duration: ${session.duration} minutes

AI SUMMARY:
-----------
${aiSummary.summary || aiSummary || 'N/A'}

KEY TAKEAWAYS:
--------------
${(aiSummary.keyTakeaways || []).join('\n- ') || 'N/A'}

NEXT STEPS:
-----------
${(aiSummary.tasks || []).join('\n- ') || 'N/A'}

---------------------------
Generated by SkillXchange AI
    `;

    res.setHeader('Content-Type', 'text/plain');
    res.setHeader('Content-Disposition', `attachment; filename=summary_${req.params.id}.txt`);
    res.send(content);
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
};

const parseGeminiJSON = (text) => {
  if (!text) return null;
  try {
    // 1. Direct parse attempt
    return JSON.parse(text);
  } catch (e) {
    try {
      // 2. Look for content between ```json and ```
      const jsonMatch = text.match(/```json\s*([\s\S]*?)\s*```/) || text.match(/```\s*([\s\S]*?)\s*```/);
      const cleaned = jsonMatch ? jsonMatch[1].trim() : text.trim();
      return JSON.parse(cleaned);
    } catch (e2) {
      // 3. Fallback: try to find anything that looks like { ... } or [ ... ]
      try {
        const firstBrace = text.indexOf('{');
        const lastBrace = text.lastIndexOf('}');
        const firstBracket = text.indexOf('[');
        const lastBracket = text.lastIndexOf(']');
        
        let startIdx = -1;
        let endIdx = -1;
        
        if (firstBrace !== -1 && (firstBracket === -1 || firstBrace < firstBracket)) {
          startIdx = firstBrace;
          endIdx = lastBrace;
        } else if (firstBracket !== -1) {
          startIdx = firstBracket;
          endIdx = lastBracket;
        }

        if (startIdx !== -1 && endIdx !== -1 && startIdx < endIdx) {
          return JSON.parse(text.substring(startIdx, endIdx + 1));
        }
      } catch (e3) {
         console.error('Gemini JSON extraction failed:', e3.message);
      }
    }
  }
  return null; // Return null instead of throwing to allow controller handling
};

const parseDocument = async (filePath, mimeType) => {
  try {
    if (mimeType === 'application/pdf') {
      const dataBuffer = fs.readFileSync(filePath);
      const data = await pdf(dataBuffer);
      return data.text;
    } else if (mimeType === 'application/vnd.openxmlformats-officedocument.wordprocessingml.document') {
      const result = await mammoth.extractRawText({ path: filePath });
      return result.value;
    } else if (mimeType === 'text/plain') {
      return fs.readFileSync(filePath, 'utf8');
    } else if (mimeType.startsWith('image/')) {
      const imageBuffer = fs.readFileSync(filePath);
      return imageBuffer.toString('base64');
    }
    return '';
  } catch (err) {
    console.error('Error parsing document:', err);
    return '';
  }
};

exports.doubtSolver = async (req, res) => {
  try {
    if (!geminiService.isConfigured()) {
      return res.status(503).json({ success: false, message: 'AI Service is not configured.' });
    }

    const { question, context } = req.body;
    const userId = req.user.id;
    const file = req.file;

    if (!question && !file) {
      return res.status(400).json({ success: false, message: 'Question or file is required' });
    }

    const user = await User.findById(userId);
    const userSkills = (user && user.skillsLearn) ? user.skillsLearn.join(', ') : '';

    let extractedText = '';
    let base64Image = '';

    if (file) {
      if (file.mimetype.startsWith('image/')) {
        base64Image = await parseDocument(file.path, file.mimetype);
      } else {
        extractedText = await parseDocument(file.path, file.mimetype);
      }
    }

    const userMsg = question || (file ? `[Uploaded File: ${file.originalname}]` : 'Analyze this');
    await ChatMessage.create({ userId, role: 'user', content: userMsg, context: context || 'Doubt Solver' });

    const history = await ChatMessage.find({ userId }).sort({ createdAt: -1 }).limit(5);
    const formattedHistory = history.reverse().map(msg => `${msg.role}: ${msg.content}`).join('\n');

    const promptText = `
You are an expert tutor on SkillXchange. Provide clear explanations, examples, and simplified breakdowns. Use markdown formatting (bold, italics, code blocks, lists) where appropriate.

User Skills: [${userSkills}]
Context: ${context || 'General Learning'}

Chat History:
${formattedHistory}

User Question/Request: ${question || 'Please analyze this content.'}
${extractedText ? `\nExtracted Document Text:\n${extractedText}` : ''}
`;

    let parts = [{ text: promptText }];

    if (base64Image) {
      parts.push({
        inlineData: {
          data: base64Image,
          mimeType: file.mimetype
        }
      });
    }

    let result;
    try {
      console.log("Generating Gemini Response for Doubt Solver via Service...");
      result = await geminiService.generateContent(parts);
    } catch (geminiErr) {
      console.error("Gemini API Error in Doubt Solver:", geminiErr);
    }
    
    let answer = result ? result.response.text().trim() : '';

    // Ensure answer is not empty or malformed
    if (!answer) {
      answer = "I'm currently experiencing high demand. Please try rephrasing your question or check the community forums for similar doubts.";
    }

    await ChatMessage.create({ userId, role: 'assistant', content: answer, context: context || 'Doubt Solver' });

    if (file && fs.existsSync(file.path)) {
      fs.unlinkSync(file.path);
    }

    res.status(200).json({ 
      success: true, 
      data: { 
        answer, 
        sources: ['SkillXchange AI Engine'],
        model: 'gemini-1.5-flash-fallback'
      } 
    });
  } catch (err) {
    console.error('AI Doubt Solver Controller Error:', err);
    res.status(500).json({ success: false, message: 'An unexpected error occurred.' });
  }
};

exports.aiTutor = async (req, res) => {
  try {
    if (!geminiService.isConfigured()) {
      return res.status(503).json({ success: false, message: 'AI Service is not configured.' });
    }

    const { topic, sessionId } = req.body;

    if (!topic) {
      return res.status(400).json({ success: false, message: 'Topic is required' });
    }

    const prompt = `
      You are an expert teacher on SkillXchange acting as a substitute tutor.
      Topic: ${topic}
      
      Generate a structured teaching session. Return your response ONLY as a JSON object, exactly matching this schema:
      {
        "topic": "The exact topic name",
        "explanation": "A thorough, beginner-friendly explanation",
        "stepByStep": ["Step 1...", "Step 2...", "Step 3..."],
        "examples": ["Example 1...", "Example 2..."],
        "miniQuiz": [
          {"question": "Q1", "options": ["A", "B", "C"], "correctAnswer": "A"},
          {"question": "Q2", "options": ["A", "B", "C"], "correctAnswer": "B"}
        ]
      }
    `;

    let sessionData = null;
    try {
      console.log("Generating Gemini Response for AI Tutor via Service...");
      const result = await geminiService.generateContent(prompt, { generationConfig: { responseMimeType: "application/json" } });
      sessionData = parseGeminiJSON(result.response.text());
    } catch (geminiErr) {
      console.error("Gemini API Error in AI Tutor:", geminiErr);
    }

    if (!sessionData) {
      console.warn("AI Tutor JSON parse failed or rate limited, using fallback structured data.");
      sessionData = {
        topic: topic,
        explanation: "Our AI is experiencing high demand. Here's a quick overview: " + topic + " is a critical skill in modern industry. We recommend exploring official documentation and peer sessions.",
        stepByStep: ["Research basics", "Practice fundamentals", "Build a project"],
        examples: ["Basic implementation", "Advanced use-case"],
        miniQuiz: [{question: "What is the first step in learning " + topic + "?", options: ["Research", "Give up", "Wait"], correctAnswer: "Research"}]
      };
    }

    if (sessionId) {
       const Session = require('../models/Session');
       const session = await findSessionByIdOrCustomId(sessionId);
       if (session) {
         session.status = 'ai-substitute';
         session.notes = `AI Tutor Session for ${topic}`;
         await session.save();
       }
    }

    res.status(200).json({
      success: true,
      data: sessionData
    });
  } catch (err) {
    console.error('AI Tutor Controller Error:', err);
    res.status(500).json({ success: false, message: `An unexpected error occurred.` });
  }
};

exports.sessionSummary = async (req, res) => {
  try {
    if (!geminiService.isConfigured()) {
      return res.status(503).json({ success: false, message: 'AI Service is not configured.' });
    }

    const { sessionId, topic, notes } = req.body;
    const file = req.file;

    let sessionTopic = topic;
    const Session = require('../models/Session');
    
    let extraContext = '';
    if (sessionId) {
      const session = await findSessionByIdOrCustomId(sessionId);
      if (session && session.aiSummary && !file) {
        console.log("Returning existing AI summary from database...");
        return res.status(200).json({
          success: true,
          data: JSON.parse(session.aiSummary)
        });
      }
      if (session && !topic) sessionTopic = session.topic;
    }

    if (!sessionTopic && !file) {
      return res.status(400).json({ success: false, message: 'Topic or session materials required' });
    }

    if (file && !file.mimetype.startsWith('audio') && !file.mimetype.startsWith('video')) {
      extraContext = await parseDocument(file.path, file.mimetype);
    }

    const prompt = `
      Analyze this learning session on "${sessionTopic || 'Uploaded Materials'}".
      Session Notes: ${notes || 'No specific notes provided.'}
      ${extraContext ? `\nExtracted Content from Session Materials:\n${extraContext}` : ''}

      Generate a high-quality summary of the session based on the provided context or attached files.
      Return your response ONLY as a JSON object, exactly matching this schema:
      {
        "summary": "Brief overall summary",
        "keyTakeaways": ["Concept 1", "Concept 2"],
        "mistakes": ["Potential pitfall 1", "Potential pitfall 2"],
        "tasks": ["Task 1", "Task 2"],
        "nextSteps": ["What to learn next"]
      }
    `;

    let parts = [{ text: prompt }];
    let uploadResult = null;

    if (file && (file.mimetype.startsWith('audio') || file.mimetype.startsWith('video') || file.mimetype === 'application/pdf')) {
        console.log("Uploading file to Gemini File Manager...");
        uploadResult = await geminiService.fileManager.uploadFile(file.path, {
            mimeType: file.mimetype,
            displayName: file.originalname,
        });
        parts.push({
            fileData: {
                mimeType: uploadResult.file.mimeType,
                fileUri: uploadResult.file.uri
            }
        });
    }

    let analysis = null;
    try {
      console.log("Generating Gemini Response for Session Summary via Service...");
      const result = await geminiService.generateContent(parts, { generationConfig: { responseMimeType: "application/json" } });
      analysis = parseGeminiJSON(result.response.text());
    } catch (geminiErr) {
      console.error("Gemini API Error in Session Summary:", geminiErr);
    }

    if (!analysis) {
      console.warn("Session Summary JSON parse failed or rate limited, using fallback analysis.");
      analysis = {
        summary: "We captured your session on " + (sessionTopic || "the topic") + ". The discussion focused on core principles and practical applications.",
        keyTakeaways: ["Interactive learning achieved", "Concept explored"],
        mistakes: ["N/A"],
        tasks: ["Review session notes", "Practice core concepts"],
        nextSteps: ["Attend next peer group session"]
      };
    }

    if (sessionId) {
      const session = await findSessionByIdOrCustomId(sessionId);
      if (session) {
        session.aiSummary = JSON.stringify(analysis);
        await session.save();
      }
    }

    if (file && fs.existsSync(file.path)) {
      fs.unlinkSync(file.path);
    }

    res.status(200).json({
      success: true,
      data: {
        ...analysis,
        sessionId
      }
    });
  } catch (err) {
    console.error('AI Session Summary Controller Error:', err);
    if (req.file && fs.existsSync(req.file.path)) fs.unlinkSync(req.file.path);
    res.status(500).json({ success: false, message: 'An unexpected error occurred.' });
  }
};

exports.generatePath = async (req, res) => {
  try {
    if (!geminiService.isConfigured()) {
      return res.status(503).json({ success: false, message: 'AI Service is not configured.' });
    }

    const { skill } = req.body;

    if (!skill) {
      return res.status(400).json({ success: false, message: 'Skill is required' });
    }

    const prompt = `
      Create a comprehensive learning roadmap for "${skill}".
      Return your response ONLY as a JSON object, exactly matching this schema:
      {
        "skill": "${skill}",
        "roadmap": {
          "beginner": { "topics": ["str1", "str2"], "tasks": ["str1"], "time": "str", "mentors": "str" },
          "intermediate": { "topics": ["str1", "str2"], "tasks": ["str1"], "time": "str", "mentors": "str" },
          "advanced": { "topics": ["str1", "str2"], "tasks": ["str1"], "time": "str", "mentors": "str" }
        }
      }
    `;

    let roadmapData = null;
    try {
      console.log("Generating Gemini Response for Learning Path via Service...");
      const result = await geminiService.generateContent(prompt, { generationConfig: { responseMimeType: "application/json" } });
      roadmapData = parseGeminiJSON(result.response.text());
    } catch (geminiErr) {
      console.error("Gemini API Error in Learning Path:", geminiErr);
    }
    
    if (!roadmapData || !roadmapData.roadmap) {
      console.warn("AI Roadmap JSON parse failed or rate limited, using fallback.");
      roadmapData = {
        skill,
        roadmap: {
          beginner: { topics: ["Fundamentals of " + skill, "Basic syntax and tools", "First project"], tasks: ["Setup environment"], time: "1-2 weeks", mentors: "Community support" },
          intermediate: { topics: ["Advanced " + skill + " patterns", "Optimizing workflows"], tasks: ["Build a complex app"], time: "3-4 weeks", mentors: "Expert mentors" },
          advanced: { topics: ["Mastering " + skill, "Architectural design"], tasks: ["Open source contribution"], time: "Ongoing", mentors: "Industry leaders" }
        }
      };
    }

    const LearningPath = require('../models/LearningPath');
    const path = await LearningPath.findOneAndUpdate(
      { userId: req.user.id, skill },
      {
        skill,
        milestones: [
          ...roadmapData.roadmap.beginner.topics.map(t => ({ title: `[Beginner] ${t}` })),
          ...roadmapData.roadmap.intermediate.topics.map(t => ({ title: `[Intermediate] ${t}` })),
          ...roadmapData.roadmap.advanced.topics.map(t => ({ title: `[Advanced] ${t}` }))
        ],
        level: 'beginner',
        progress: 0
      },
      { upsert: true, new: true }
    );

    res.status(200).json({
      success: true,
      data: {
        ...roadmapData,
        dbPathId: path._id
      }
    });
  } catch (err) {
    console.error('AI Learning Path Controller Error:', err);
    res.status(500).json({ success: false, message: 'An unexpected error occurred.' });
  }
};

exports.meetingSummary = async (req, res) => {
  try {
    if (!geminiService.isConfigured() || !geminiService.fileManager) {
      return res.status(503).json({ success: false, message: 'AI Service is not configured.' });
    }

    const { sessionId } = req.body;
    const file = req.file;

    if (!sessionId || !file) {
      return res.status(400).json({ success: false, message: 'Session ID and audio file are required' });
    }

    const Session = require('../models/Session');
    const session = await Session.findOne({ sessionId });
    if (!session) {
      return res.status(404).json({ success: false, message: 'Session not found' });
    }

    let summaryData = null;
    let transcriptText = "Audio transcribed successfully.";

    try {
      console.log("Uploading audio file to Gemini File Manager...");
      const uploadResult = await geminiService.fileManager.uploadFile(file.path, {
          mimeType: file.mimetype,
          displayName: file.originalname,
      });

      const prompt = `
        You are an expert educational AI. 
        Analyze the attached audio recording of a peer-learning session on the topic "${session.topic}".
        
        First, transcribe the core meaning of the session, and then summarize it.
        Return your response ONLY as a JSON object, exactly matching this schema:
        {
          "transcriptText": "A robust summary of what was actually spoken in the audio.",
          "summary": "A concise 2-3 sentence overview of the session",
          "keyTakeaways": ["Concept 1", "Concept 2"],
          "mistakes": ["Any misconceptions or errors discussed"],
          "tasks": ["Actionable tasks for the learner"],
          "nextSteps": ["What the learner should focus on next"]
        }
      `;

      console.log("Generating Gemini Response for Meeting Summary via Service...");
      const result = await geminiService.generateContent([
          { fileData: { mimeType: uploadResult.file.mimeType, fileUri: uploadResult.file.uri } },
          { text: prompt }
      ], { generationConfig: { responseMimeType: "application/json" } });

      summaryData = parseGeminiJSON(result.response.text());
      if (summaryData && summaryData.transcriptText) {
        transcriptText = summaryData.transcriptText;
        delete summaryData.transcriptText;
      }
    } catch (geminiErr) {
      console.error("Gemini API Error in Meeting Summary:", geminiErr);
    }

    if (!summaryData) {
      console.warn("Meeting Summary JSON parse failed or rate limited, using fallback analysis.");
      summaryData = {
        summary: "The session recording was processed successfully. Due to high demand, a detailed analysis is not currently available.",
        keyTakeaways: ["Session attended", "Concepts discussed"],
        mistakes: ["N/A"],
        tasks: ["Review your notes"],
        nextSteps: ["Practice the concepts covered"]
      };
    }

    session.aiSummary = JSON.stringify(summaryData);
    await session.save();

    if (fs.existsSync(file.path)) {
      fs.unlinkSync(file.path);
    }

    res.status(200).json({
      success: true,
      data: summaryData,
      transcript: transcriptText
    });

  } catch (err) {
    console.error('AI Meeting Summary Controller Error:', err);
    if (req.file && fs.existsSync(req.file.path)) fs.unlinkSync(req.file.path);
    res.status(500).json({ success: false, message: 'An unexpected error occurred.' });
  }
};
exports.getSummaries = async (req, res) => {
  try {
    const Session = require('../models/Session');
    const sessions = await Session.find({
      $or: [{ learnerId: req.user.id }, { mentorId: req.user.id }],
      aiSummary: { $exists: true, $ne: '', $ne: null }
    }).sort({ createdAt: -1 });

    const summaries = sessions.map(s => {
      let parsedSummary = null;
      try {
        parsedSummary = typeof s.aiSummary === 'string' ? JSON.parse(s.aiSummary) : s.aiSummary;
      } catch (e) {
        console.error(`Failed to parse aiSummary for session ${s._id}:`, e.message);
        // Fallback to a safe object if parsing fails
        parsedSummary = { summary: 'Summary unavailable', keyTakeaways: [], tasks: [] };
      }
      
      return {
        id: s._id,
        topic: s.topic,
        date: s.createdAt,
        summary: parsedSummary
      };
    });

    res.status(200).json({ success: true, data: summaries });
  } catch (err) {
    console.error('Error fetching summaries:', err);
    res.status(500).json({ success: false, message: 'Server error' });
  }
};
exports.getChatHistory = async (req, res) => {
  try {
    const history = await ChatMessage.find({ 
      userId: req.user.id,
      context: 'Doubt Solver' 
    }).sort({ createdAt: 1 }).limit(20);

    const formatted = history.map(msg => ({
      text: msg.content,
      sender: msg.role === 'assistant' ? 'ai' : 'user',
      id: msg._id
    }));

    res.status(200).json({ success: true, data: formatted });
  } catch (err) {
    console.error('Error fetching chat history:', err);
    res.status(500).json({ success: false, message: 'Server error' });
  }
};
